# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cac70a3e07dbfd652195bb1671816cff1a01ed15d663b6044c542f0355f038fdc45851c31bf0ad94bfce09e2a55e0f5bbc3de633c78d76adea0daefa49abbbc4

test:
  secret_key_base: 2366000ed22bc26bb136f2ae6366eecbd102e5c78aa9de14209f7b15ade95456d685d4baf0557e40e946b64a910f20fa694b0023855d79181da0875dd054bcb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
